/*
 * Vencord, a modification for Discord's desktop app
 * Copyright (c) 2023 Vendicated and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import { definePluginSettings } from "@api/Settings";
import { OptionType } from "@utils/types";

export const settings = definePluginSettings({
    receivedInput: {
        type: OptionType.SELECT,
        description: "Language that received messages should be translated from",
        options: settings.store.service === "google" ? [
            { label: "Detect language", value: "auto", default : true },
            { label: "Afrikaans", value: "af" },
            { label: "Albanian", value: "sq" },
            { label: "Amharic", value: "am" },
            { label: "Arabic", value: "ar" },
            { label: "Armenian", value: "hy" },
            { label: "Assamese", value: "as" },
            { label: "Aymara", value: "ay" },
            { label: "Azerbaijani", value: "az" },
            { label: "Bambara", value: "bm" },
            { label: "Basque", value: "eu" },
            { label: "Belarusian", value: "be" },
            { label: "Bengali", value: "bn" },
            { label: "Bhojpuri", value: "bho" },
            { label: "Bosnian", value: "bs" },
            { label: "Bulgarian", value: "bg" },
            { label: "Catalan", value: "ca" },
            { label: "Cebuano", value: "ceb" },
            { label: "Chichewa", value: "ny" },
            { label: "Chinese (Simplified)", value: "zh-CN" },
            { label: "Chinese (Traditional)", value: "zh-TW" },
            { label: "Corsican", value: "co" },
            { label: "Croatian", value: "hr" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dhivehi", value: "dv" },
            { label: "Dogri", value: "doi" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en" },
            { label: "Esperanto", value: "eo" },
            { label: "Estonian", value: "et" },
            { label: "Ewe", value: "ee" },
            { label: "Filipino", value: "tl" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "Frisian", value: "fy" },
            { label: "Galician", value: "gl" },
            { label: "Georgian", value: "ka" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Guarani", value: "gn" },
            { label: "Gujarati", value: "gu" },
            { label: "Haitian Creole", value: "ht" },
            { label: "Hausa", value: "ha" },
            { label: "Hawaiian", value: "haw" },
            { label: "Hebrew", value: "iw" },
            { label: "Hindi", value: "hi" },
            { label: "Hmong", value: "hmn" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Igbo", value: "ig" },
            { label: "Ilocano", value: "ilo" },
            { label: "Indonesian", value: "id" },
            { label: "Irish", value: "ga" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Javanese", value: "jw" },
            { label: "Kannada", value: "kn" },
            { label: "Kazakh", value: "kk" },
            { label: "Khmer", value: "km" },
            { label: "Kinyarwanda", value: "rw" },
            { label: "Konkani", value: "gom" },
            { label: "Korean", value: "ko" },
            { label: "Krio", value: "kri" },
            { label: "Kurdish (Kurmanji)", value: "ku" },
            { label: "Kurdish (Sorani)", value: "ckb" },
            { label: "Kyrgyz", value: "ky" },
            { label: "Lao", value: "lo" },
            { label: "Latin", value: "la" },
            { label: "Latvian", value: "lv" },
            { label: "Lingala", value: "ln" },
            { label: "Lithuanian", value: "lt" },
            { label: "Luganda", value: "lg" },
            { label: "Luxembourgish", value: "lb" },
            { label: "Macedonian", value: "mk" },
            { label: "Maithili", value: "mai" },
            { label: "Malagasy", value: "mg" },
            { label: "Malay", value: "ms" },
            { label: "Malayalam", value: "ml" },
            { label: "Maltese", value: "mt" },
            { label: "Maori", value: "mi" },
            { label: "Marathi", value: "mr" },
            { label: "Meiteilon (Manipuri)", value: "mni-Mtei" },
            { label: "Mizo", value: "lus" },
            { label: "Mongolian", value: "mn" },
            { label: "Myanmar (Burmese)", value: "my" },
            { label: "Nepali", value: "ne" },
            { label: "Norwegian", value: "no" },
            { label: "Odia (Oriya)", value: "or" },
            { label: "Oromo", value: "om" },
            { label: "Pashto", value: "ps" },
            { label: "Persian", value: "fa" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Punjabi", value: "pa" },
            { label: "Quechua", value: "qu" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Samoan", value: "sm" },
            { label: "Sanskrit", value: "sa" },
            { label: "Scots Gaelic", value: "gd" },
            { label: "Sepedi", value: "nso" },
            { label: "Serbian", value: "sr" },
            { label: "Sesotho", value: "st" },
            { label: "Shona", value: "sn" },
            { label: "Sindhi", value: "sd" },
            { label: "Sinhala", value: "si" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Somali", value: "so" },
            { label: "Spanish", value: "es" },
            { label: "Sundanese", value: "su" },
            { label: "Swahili", value: "sw" },
            { label: "Swedish", value: "sv" },
            { label: "Tajik", value: "tg" },
            { label: "Tamil", value: "ta" },
            { label: "Tatar", value: "tt" },
            { label: "Telugu", value: "te" },
            { label: "Thai", value: "th" },
            { label: "Tigrinya", value: "ti" },
            { label: "Tsonga", value: "ts" },
            { label: "Turkish", value: "tr" },
            { label: "Turkmen", value: "tk" },
            { label: "Twi", value: "ak" },
            { label: "Ukrainian", value: "uk" },
            { label: "Urdu", value: "ur" },
            { label: "Uyghur", value: "ug" },
            { label: "Uzbek", value: "uz" },
            { label: "Vietnamese", value: "vi" },
            { label: "Welsh", value: "cy" },
            { label: "Xhosa", value: "xh" },
            { label: "Yiddish", value: "yi" },
            { label: "Yoruba", value: "yo" },
            { label: "Zulu", value: "zu" }
        ] as const : [
            { label: "Detect language", value: "", default : true },
            { label: "Arabic", value: "ar" },
            { label: "Bulgarian", value: "bg" },
            { label: "Chinese (Simplified)", value: "zh-hans" },
            { label: "Chinese (Traditional)", value: "zh-hant" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English (American)", value: "en-us" },
            { label: "English (British)", value: "en-gb" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Hungarian", value: "hu" },
            { label: "Indonesian", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuanian", value: "lt" },
            { label: "Norwegian", value: "nb" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese (Brazilian)", value: "pt-br" },
            { label: "Portuguese (European)", value: "pt-pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" }
        ] as const
    },
    receivedOutput: {
        type: OptionType.SELECT,
        description: "Language that received messages should be translated to",
        options: settings.store.service === "google" ? [
            { label: "Detect language", value: "auto" },
            { label: "Afrikaans", value: "af" },
            { label: "Albanian", value: "sq" },
            { label: "Amharic", value: "am" },
            { label: "Arabic", value: "ar" },
            { label: "Armenian", value: "hy" },
            { label: "Assamese", value: "as" },
            { label: "Aymara", value: "ay" },
            { label: "Azerbaijani", value: "az" },
            { label: "Bambara", value: "bm" },
            { label: "Basque", value: "eu" },
            { label: "Belarusian", value: "be" },
            { label: "Bengali", value: "bn" },
            { label: "Bhojpuri", value: "bho" },
            { label: "Bosnian", value: "bs" },
            { label: "Bulgarian", value: "bg" },
            { label: "Catalan", value: "ca" },
            { label: "Cebuano", value: "ceb" },
            { label: "Chichewa", value: "ny" },
            { label: "Chinese (Simplified)", value: "zh-CN" },
            { label: "Chinese (Traditional)", value: "zh-TW" },
            { label: "Corsican", value: "co" },
            { label: "Croatian", value: "hr" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dhivehi", value: "dv" },
            { label: "Dogri", value: "doi" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en", default : true },
            { label: "Esperanto", value: "eo" },
            { label: "Estonian", value: "et" },
            { label: "Ewe", value: "ee" },
            { label: "Filipino", value: "tl" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "Frisian", value: "fy" },
            { label: "Galician", value: "gl" },
            { label: "Georgian", value: "ka" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Guarani", value: "gn" },
            { label: "Gujarati", value: "gu" },
            { label: "Haitian Creole", value: "ht" },
            { label: "Hausa", value: "ha" },
            { label: "Hawaiian", value: "haw" },
            { label: "Hebrew", value: "iw" },
            { label: "Hindi", value: "hi" },
            { label: "Hmong", value: "hmn" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Igbo", value: "ig" },
            { label: "Ilocano", value: "ilo" },
            { label: "Indonesian", value: "id" },
            { label: "Irish", value: "ga" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Javanese", value: "jw" },
            { label: "Kannada", value: "kn" },
            { label: "Kazakh", value: "kk" },
            { label: "Khmer", value: "km" },
            { label: "Kinyarwanda", value: "rw" },
            { label: "Konkani", value: "gom" },
            { label: "Korean", value: "ko" },
            { label: "Krio", value: "kri" },
            { label: "Kurdish (Kurmanji)", value: "ku" },
            { label: "Kurdish (Sorani)", value: "ckb" },
            { label: "Kyrgyz", value: "ky" },
            { label: "Lao", value: "lo" },
            { label: "Latin", value: "la" },
            { label: "Latvian", value: "lv" },
            { label: "Lingala", value: "ln" },
            { label: "Lithuanian", value: "lt" },
            { label: "Luganda", value: "lg" },
            { label: "Luxembourgish", value: "lb" },
            { label: "Macedonian", value: "mk" },
            { label: "Maithili", value: "mai" },
            { label: "Malagasy", value: "mg" },
            { label: "Malay", value: "ms" },
            { label: "Malayalam", value: "ml" },
            { label: "Maltese", value: "mt" },
            { label: "Maori", value: "mi" },
            { label: "Marathi", value: "mr" },
            { label: "Meiteilon (Manipuri)", value: "mni-Mtei" },
            { label: "Mizo", value: "lus" },
            { label: "Mongolian", value: "mn" },
            { label: "Myanmar (Burmese)", value: "my" },
            { label: "Nepali", value: "ne" },
            { label: "Norwegian", value: "no" },
            { label: "Odia (Oriya)", value: "or" },
            { label: "Oromo", value: "om" },
            { label: "Pashto", value: "ps" },
            { label: "Persian", value: "fa" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Punjabi", value: "pa" },
            { label: "Quechua", value: "qu" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Samoan", value: "sm" },
            { label: "Sanskrit", value: "sa" },
            { label: "Scots Gaelic", value: "gd" },
            { label: "Sepedi", value: "nso" },
            { label: "Serbian", value: "sr" },
            { label: "Sesotho", value: "st" },
            { label: "Shona", value: "sn" },
            { label: "Sindhi", value: "sd" },
            { label: "Sinhala", value: "si" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Somali", value: "so" },
            { label: "Spanish", value: "es" },
            { label: "Sundanese", value: "su" },
            { label: "Swahili", value: "sw" },
            { label: "Swedish", value: "sv" },
            { label: "Tajik", value: "tg" },
            { label: "Tamil", value: "ta" },
            { label: "Tatar", value: "tt" },
            { label: "Telugu", value: "te" },
            { label: "Thai", value: "th" },
            { label: "Tigrinya", value: "ti" },
            { label: "Tsonga", value: "ts" },
            { label: "Turkish", value: "tr" },
            { label: "Turkmen", value: "tk" },
            { label: "Twi", value: "ak" },
            { label: "Ukrainian", value: "uk" },
            { label: "Urdu", value: "ur" },
            { label: "Uyghur", value: "ug" },
            { label: "Uzbek", value: "uz" },
            { label: "Vietnamese", value: "vi" },
            { label: "Welsh", value: "cy" },
            { label: "Xhosa", value: "xh" },
            { label: "Yiddish", value: "yi" },
            { label: "Yoruba", value: "yo" },
            { label: "Zulu", value: "zu" }
        ] as const : [
            { label: "Detect language", value: "" },
            { label: "Arabic", value: "ar" },
            { label: "Bulgarian", value: "bg" },
            { label: "Chinese (Simplified)", value: "zh-hans" },
            { label: "Chinese (Traditional)", value: "zh-hant" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English (American)", value: "en-us", default : true },
            { label: "English (British)", value: "en-gb" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Hungarian", value: "hu" },
            { label: "Indonesian", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuanian", value: "lt" },
            { label: "Norwegian", value: "nb" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese (Brazilian)", value: "pt-br" },
            { label: "Portuguese (European)", value: "pt-pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" }
        ] as const
    },
    sentInput: {
        type: OptionType.STRING,
        description: "Language that your own messages should be translated from",
        options: settings.store.service === "google" ? [
            { label: "Detect language", value: "auto", default : true },
            { label: "Afrikaans", value: "af" },
            { label: "Albanian", value: "sq" },
            { label: "Amharic", value: "am" },
            { label: "Arabic", value: "ar" },
            { label: "Armenian", value: "hy" },
            { label: "Assamese", value: "as" },
            { label: "Aymara", value: "ay" },
            { label: "Azerbaijani", value: "az" },
            { label: "Bambara", value: "bm" },
            { label: "Basque", value: "eu" },
            { label: "Belarusian", value: "be" },
            { label: "Bengali", value: "bn" },
            { label: "Bhojpuri", value: "bho" },
            { label: "Bosnian", value: "bs" },
            { label: "Bulgarian", value: "bg" },
            { label: "Catalan", value: "ca" },
            { label: "Cebuano", value: "ceb" },
            { label: "Chichewa", value: "ny" },
            { label: "Chinese (Simplified)", value: "zh-CN" },
            { label: "Chinese (Traditional)", value: "zh-TW" },
            { label: "Corsican", value: "co" },
            { label: "Croatian", value: "hr" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dhivehi", value: "dv" },
            { label: "Dogri", value: "doi" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en" },
            { label: "Esperanto", value: "eo" },
            { label: "Estonian", value: "et" },
            { label: "Ewe", value: "ee" },
            { label: "Filipino", value: "tl" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "Frisian", value: "fy" },
            { label: "Galician", value: "gl" },
            { label: "Georgian", value: "ka" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Guarani", value: "gn" },
            { label: "Gujarati", value: "gu" },
            { label: "Haitian Creole", value: "ht" },
            { label: "Hausa", value: "ha" },
            { label: "Hawaiian", value: "haw" },
            { label: "Hebrew", value: "iw" },
            { label: "Hindi", value: "hi" },
            { label: "Hmong", value: "hmn" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Igbo", value: "ig" },
            { label: "Ilocano", value: "ilo" },
            { label: "Indonesian", value: "id" },
            { label: "Irish", value: "ga" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Javanese", value: "jw" },
            { label: "Kannada", value: "kn" },
            { label: "Kazakh", value: "kk" },
            { label: "Khmer", value: "km" },
            { label: "Kinyarwanda", value: "rw" },
            { label: "Konkani", value: "gom" },
            { label: "Korean", value: "ko" },
            { label: "Krio", value: "kri" },
            { label: "Kurdish (Kurmanji)", value: "ku" },
            { label: "Kurdish (Sorani)", value: "ckb" },
            { label: "Kyrgyz", value: "ky" },
            { label: "Lao", value: "lo" },
            { label: "Latin", value: "la" },
            { label: "Latvian", value: "lv" },
            { label: "Lingala", value: "ln" },
            { label: "Lithuanian", value: "lt" },
            { label: "Luganda", value: "lg" },
            { label: "Luxembourgish", value: "lb" },
            { label: "Macedonian", value: "mk" },
            { label: "Maithili", value: "mai" },
            { label: "Malagasy", value: "mg" },
            { label: "Malay", value: "ms" },
            { label: "Malayalam", value: "ml" },
            { label: "Maltese", value: "mt" },
            { label: "Maori", value: "mi" },
            { label: "Marathi", value: "mr" },
            { label: "Meiteilon (Manipuri)", value: "mni-Mtei" },
            { label: "Mizo", value: "lus" },
            { label: "Mongolian", value: "mn" },
            { label: "Myanmar (Burmese)", value: "my" },
            { label: "Nepali", value: "ne" },
            { label: "Norwegian", value: "no" },
            { label: "Odia (Oriya)", value: "or" },
            { label: "Oromo", value: "om" },
            { label: "Pashto", value: "ps" },
            { label: "Persian", value: "fa" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Punjabi", value: "pa" },
            { label: "Quechua", value: "qu" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Samoan", value: "sm" },
            { label: "Sanskrit", value: "sa" },
            { label: "Scots Gaelic", value: "gd" },
            { label: "Sepedi", value: "nso" },
            { label: "Serbian", value: "sr" },
            { label: "Sesotho", value: "st" },
            { label: "Shona", value: "sn" },
            { label: "Sindhi", value: "sd" },
            { label: "Sinhala", value: "si" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Somali", value: "so" },
            { label: "Spanish", value: "es" },
            { label: "Sundanese", value: "su" },
            { label: "Swahili", value: "sw" },
            { label: "Swedish", value: "sv" },
            { label: "Tajik", value: "tg" },
            { label: "Tamil", value: "ta" },
            { label: "Tatar", value: "tt" },
            { label: "Telugu", value: "te" },
            { label: "Thai", value: "th" },
            { label: "Tigrinya", value: "ti" },
            { label: "Tsonga", value: "ts" },
            { label: "Turkish", value: "tr" },
            { label: "Turkmen", value: "tk" },
            { label: "Twi", value: "ak" },
            { label: "Ukrainian", value: "uk" },
            { label: "Urdu", value: "ur" },
            { label: "Uyghur", value: "ug" },
            { label: "Uzbek", value: "uz" },
            { label: "Vietnamese", value: "vi" },
            { label: "Welsh", value: "cy" },
            { label: "Xhosa", value: "xh" },
            { label: "Yiddish", value: "yi" },
            { label: "Yoruba", value: "yo" },
            { label: "Zulu", value: "zu" }
        ] as const : [
            { label: "Detect language", value: "", default : true },
            { label: "Arabic", value: "ar" },
            { label: "Bulgarian", value: "bg" },
            { label: "Chinese (Simplified)", value: "zh-hans" },
            { label: "Chinese (Traditional)", value: "zh-hant" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English (American)", value: "en-us" },
            { label: "English (British)", value: "en-gb" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Hungarian", value: "hu" },
            { label: "Indonesian", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuanian", value: "lt" },
            { label: "Norwegian", value: "nb" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese (Brazilian)", value: "pt-br" },
            { label: "Portuguese (European)", value: "pt-pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" }
        ] as const
    },
    sentOutput: {
        type: OptionType.SELECT,
        description: "Language that your own messages should be translated to",
        options: settings.store.service === "google" ? [
            { label: "Detect language", value: "auto" },
            { label: "Afrikaans", value: "af" },
            { label: "Albanian", value: "sq" },
            { label: "Amharic", value: "am" },
            { label: "Arabic", value: "ar" },
            { label: "Armenian", value: "hy" },
            { label: "Assamese", value: "as" },
            { label: "Aymara", value: "ay" },
            { label: "Azerbaijani", value: "az" },
            { label: "Bambara", value: "bm" },
            { label: "Basque", value: "eu" },
            { label: "Belarusian", value: "be" },
            { label: "Bengali", value: "bn" },
            { label: "Bhojpuri", value: "bho" },
            { label: "Bosnian", value: "bs" },
            { label: "Bulgarian", value: "bg" },
            { label: "Catalan", value: "ca" },
            { label: "Cebuano", value: "ceb" },
            { label: "Chichewa", value: "ny" },
            { label: "Chinese (Simplified)", value: "zh-CN" },
            { label: "Chinese (Traditional)", value: "zh-TW" },
            { label: "Corsican", value: "co" },
            { label: "Croatian", value: "hr" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dhivehi", value: "dv" },
            { label: "Dogri", value: "doi" },
            { label: "Dutch", value: "nl" },
            { label: "English", value: "en", default : true },
            { label: "Esperanto", value: "eo" },
            { label: "Estonian", value: "et" },
            { label: "Ewe", value: "ee" },
            { label: "Filipino", value: "tl" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "Frisian", value: "fy" },
            { label: "Galician", value: "gl" },
            { label: "Georgian", value: "ka" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Guarani", value: "gn" },
            { label: "Gujarati", value: "gu" },
            { label: "Haitian Creole", value: "ht" },
            { label: "Hausa", value: "ha" },
            { label: "Hawaiian", value: "haw" },
            { label: "Hebrew", value: "iw" },
            { label: "Hindi", value: "hi" },
            { label: "Hmong", value: "hmn" },
            { label: "Hungarian", value: "hu" },
            { label: "Icelandic", value: "is" },
            { label: "Igbo", value: "ig" },
            { label: "Ilocano", value: "ilo" },
            { label: "Indonesian", value: "id" },
            { label: "Irish", value: "ga" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Javanese", value: "jw" },
            { label: "Kannada", value: "kn" },
            { label: "Kazakh", value: "kk" },
            { label: "Khmer", value: "km" },
            { label: "Kinyarwanda", value: "rw" },
            { label: "Konkani", value: "gom" },
            { label: "Korean", value: "ko" },
            { label: "Krio", value: "kri" },
            { label: "Kurdish (Kurmanji)", value: "ku" },
            { label: "Kurdish (Sorani)", value: "ckb" },
            { label: "Kyrgyz", value: "ky" },
            { label: "Lao", value: "lo" },
            { label: "Latin", value: "la" },
            { label: "Latvian", value: "lv" },
            { label: "Lingala", value: "ln" },
            { label: "Lithuanian", value: "lt" },
            { label: "Luganda", value: "lg" },
            { label: "Luxembourgish", value: "lb" },
            { label: "Macedonian", value: "mk" },
            { label: "Maithili", value: "mai" },
            { label: "Malagasy", value: "mg" },
            { label: "Malay", value: "ms" },
            { label: "Malayalam", value: "ml" },
            { label: "Maltese", value: "mt" },
            { label: "Maori", value: "mi" },
            { label: "Marathi", value: "mr" },
            { label: "Meiteilon (Manipuri)", value: "mni-Mtei" },
            { label: "Mizo", value: "lus" },
            { label: "Mongolian", value: "mn" },
            { label: "Myanmar (Burmese)", value: "my" },
            { label: "Nepali", value: "ne" },
            { label: "Norwegian", value: "no" },
            { label: "Odia (Oriya)", value: "or" },
            { label: "Oromo", value: "om" },
            { label: "Pashto", value: "ps" },
            { label: "Persian", value: "fa" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese", value: "pt" },
            { label: "Punjabi", value: "pa" },
            { label: "Quechua", value: "qu" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Samoan", value: "sm" },
            { label: "Sanskrit", value: "sa" },
            { label: "Scots Gaelic", value: "gd" },
            { label: "Sepedi", value: "nso" },
            { label: "Serbian", value: "sr" },
            { label: "Sesotho", value: "st" },
            { label: "Shona", value: "sn" },
            { label: "Sindhi", value: "sd" },
            { label: "Sinhala", value: "si" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Somali", value: "so" },
            { label: "Spanish", value: "es" },
            { label: "Sundanese", value: "su" },
            { label: "Swahili", value: "sw" },
            { label: "Swedish", value: "sv" },
            { label: "Tajik", value: "tg" },
            { label: "Tamil", value: "ta" },
            { label: "Tatar", value: "tt" },
            { label: "Telugu", value: "te" },
            { label: "Thai", value: "th" },
            { label: "Tigrinya", value: "ti" },
            { label: "Tsonga", value: "ts" },
            { label: "Turkish", value: "tr" },
            { label: "Turkmen", value: "tk" },
            { label: "Twi", value: "ak" },
            { label: "Ukrainian", value: "uk" },
            { label: "Urdu", value: "ur" },
            { label: "Uyghur", value: "ug" },
            { label: "Uzbek", value: "uz" },
            { label: "Vietnamese", value: "vi" },
            { label: "Welsh", value: "cy" },
            { label: "Xhosa", value: "xh" },
            { label: "Yiddish", value: "yi" },
            { label: "Yoruba", value: "yo" },
            { label: "Zulu", value: "zu" }
        ] as const : [
            { label: "Detect language", value: "", default : true },
            { label: "Arabic", value: "ar" },
            { label: "Bulgarian", value: "bg" },
            { label: "Chinese (Simplified)", value: "zh-hans" },
            { label: "Chinese (Traditional)", value: "zh-hant" },
            { label: "Czech", value: "cs" },
            { label: "Danish", value: "da" },
            { label: "Dutch", value: "nl" },
            { label: "English (American)", value: "en-us", default : true },
            { label: "English (British)", value: "en-gb" },
            { label: "Estonian", value: "et" },
            { label: "Finnish", value: "fi" },
            { label: "French", value: "fr" },
            { label: "German", value: "de" },
            { label: "Greek", value: "el" },
            { label: "Hungarian", value: "hu" },
            { label: "Indonesian", value: "id" },
            { label: "Italian", value: "it" },
            { label: "Japanese", value: "ja" },
            { label: "Korean", value: "ko" },
            { label: "Latvian", value: "lv" },
            { label: "Lithuanian", value: "lt" },
            { label: "Norwegian", value: "nb" },
            { label: "Polish", value: "pl" },
            { label: "Portuguese (Brazilian)", value: "pt-br" },
            { label: "Portuguese (European)", value: "pt-pt" },
            { label: "Romanian", value: "ro" },
            { label: "Russian", value: "ru" },
            { label: "Slovak", value: "sk" },
            { label: "Slovenian", value: "sl" },
            { label: "Spanish", value: "es" },
            { label: "Swedish", value: "sv" },
            { label: "Turkish", value: "tr" },
            { label: "Ukrainian", value: "uk" }
        ] as const
    },

    showChatBarButton: {
        type: OptionType.BOOLEAN,
        description: "Show translate button in chat bar",
        default: true
    },
    service: {
        type: OptionType.SELECT,
        description: IS_WEB ? "Translation service (Not supported on Web!)" : "Translation service",
        disabled: () => IS_WEB,
        options: [
            { label: "Google Translate", value: "google", default: true },
            { label: "DeepL Free", value: "deepl" },
            { label: "DeepL Pro", value: "deepl-pro" }
        ] as const,
        onChange: resetLanguageDefaults
    },
    deeplApiKey: {
        type: OptionType.STRING,
        description: "DeepL API key",
        default: "",
        placeholder: "Get your API key from https://deepl.com/your-account",
        disabled: () => IS_WEB
    },
    autoTranslate: {
        type: OptionType.BOOLEAN,
        description: "Automatically translate your messages before sending. You can also shift/right click the translate button to toggle this",
        default: false
    },
    showAutoTranslateTooltip: {
        type: OptionType.BOOLEAN,
        description: "Show a tooltip on the ChatBar button whenever a message is automatically translated",
        default: true
    },
}).withPrivateSettings<{
    showAutoTranslateAlert: boolean;
}>();

export function resetLanguageDefaults() {
    if (IS_WEB || settings.store.service === "google") {
        settings.store.receivedInput = "auto";
        settings.store.receivedOutput = "en";
        settings.store.sentInput = "auto";
        settings.store.sentOutput = "en";
    } else {
        settings.store.receivedInput = "";
        settings.store.receivedOutput = "en-us";
        settings.store.sentInput = "";
        settings.store.sentOutput = "en-us";
    }
}
